version: "3"
services:
  client:
    build:
      context: ../../../../Desktop/saendterm-master
      dockerfile: grpc/grpc_client/Dockerfile
    restart: always
    links:
      - server
    depends_on:
      - server
  server:
    build:
      context: ../../../../Desktop/saendterm-master
      dockerfile: grpc/grpc_server/Dockerfile
    restart: always
    ports:
      - "50052:50052"